version: '3.3'

services: 

  movieplex7:
    build: movieplex7
    image: movieplex7-tomee
    ports:
      - "8080:8080"
  
  react-client:
    build: react-client
    image: react-client
    ports:
      - "80:80"