version: '3.3'

services: 

  movieplex7:
    build: movieplex7
    image: 52.232.26.254/dev/movieplex7-server
    ports:
      - "8080:8080"
  
  react-client:
    build: react-client
    image: 52.232.26.254/dev/movieplex7-client
    ports:
      - "80:80"